apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-python
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: spark:3.5.3
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///data/spark_tpcbench.py
  arguments:
    - --name
    - spark
    - --benchmark
    - tpch
    - --data
    - /data/sf100
    - --queries
    - /data/queries
    - --output
    - /data/
    - --concurrency
    - "16"
  sparkVersion: 3.5.3
  driver:
    cores: 8
    memory: "32g"
    serviceAccount: spark-operator-spark
    volumeMounts:
      - name: spark-local-dir-spark-vol
        mountPath: /data
  executor:
    instances: 2
    cores: 5
    memory: "60g"
    memoryOverhead: "4g"
    volumeMounts:
      - name: spark-local-dir-spark-vol
        mountPath: /data
  volumes:
    - name: spark-local-dir-spark-vol
      persistentVolumeClaim:
        claimName: ray-pvc
