apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-python
  namespace: default
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: spark:3.5.3
  imagePullPolicy: IfNotPresent
  mainApplicationFile: local:///mnt/bigdata/spark_tpcbench.py
  arguments: 
    - --name 
    - spark
    - --benchmark 
    - tpch
    - --data 
    - /mnt/bigdata/sf100
    - --queries 
    - /mnt/bigdata/queries
    - --output 
    - /mnt/bigdata/
    - --concurrency
    - "16"
  sparkVersion: 3.5.3
  driver:
    cores: 8
    memory: "32g"
    serviceAccount: spark-operator-spark
    volumeMounts:
    - name: spark-local-dir-spark-vol
      mountPath: /mnt/bigdata
  executor:
    instances: 2
    cores: 5
    memory: "60g"
    memoryOverhead: "4g"
    volumeMounts:
    - name: spark-local-dir-spark-vol
      mountPath: /mnt/bigdata
  volumes:
    - name: spark-local-dir-spark-vol
      persistentVolumeClaim: 
        claimName: ray-pvc
